### ISSUE TITLE
Extraction of nQuire plotting script

### ISSUE THREAD

**Issue by mrmrwinter** [Gabaldonlab/karyon#3]
Hi, i think that the nQuire ploidy/CN plots look great. Would you be able to pull them out as a standalone script i could use please?

Ive spent a lot of time trying to get the allplots.py script running but have had no luck yet.

Many thanks

Mike

**Comment by MANaranjo** [comment]
Greetings,

I have created an additional script that runs the nQuire plot only. The
script is named nQuire_plot.py. Please let me know if you find any issues.

Best regards,

Miguel Naranjo-Ortiz

**Comment by mrmrwinter** [comment]
Excellent, thank you!
