### ISSUE TITLE
Running the variant calling pipeline and plots with existing assembly

### ISSUE THREAD

**Issue by alexvasilikop** [Gabaldonlab/karyon#4]
Hello,

I would like to use the pipeline for the mapping and variant calling, plotting but I would like to skip the first parts which are the assembly, reduction and proceed directly to the above steps. My assembly is already in a good state. However, bin/varcall_recipee.py does not come with documentation of the required arguments. Are the scripts also as a standalone version or does some one need to run the entire pipeline?

Thanks
Alex

**Comment by Dfupa** [comment]
Hi Alex,

You can use karyon.py with the parameters  -A/ --no_assembly and -R / -no_reduction to skip those steps in the pipeline. You would also need to provide the assembly as an input file after the no_assembly argument. ie:

`python3 karyon.py -l L1_1.fastq, L1_2.fastq -d karyon_results -T -R -A myassembly.fasta`

More in detail information is available in the [manual](https://github.com/Gabaldonlab/karyon/blob/master/Karyon_manual.pdf). 

Hope it helps!

**Comment by alexvasilikop** [comment]
Hi,

I tried to run the pipeline as yous suggested but I get an error which probably is coming from the execution of KAT, the pipeline continues after that but i did not let it run the next steps.
```
python3 /mnt/sda1/Alex/software/karyon/bin/karyon.py -l /mnt/sdc1/Illumina.GC055462-A.R1.merged.trimmed.fastq.gz /mnt/sdc1/Illumina.GC055462-A.R2.merged.trimmed.fastq.gz -d ./karyon_results -T -R -A Assembly.fasta -n 10 -o GC055462-A
```

I get the following output:
```

###############
Config. path: /mnt/sda1/Alex/software/karyon/configuration.txt
RAM Limit: 56Gb
Nodes: 10
Job ID: QCPTHV
Job name: GC055462-A
###############
Kmer Analysis Toolkit (KAT) V2.3.1


Error: Parsing Command Line: the required argument for option '--output_prefix' is missing

ERROR conda.cli.main_run:execute(47): `conda run kat comp -o` failed. (See above for error)
Error: Parsing Command Line: the required argument for option '--output_prefix' is missing

ERROR conda.cli.main_run:execute(47): `conda run kat comp -o` failed. (See above for error)
###############
KAT: 1
conda run -n redundans_env kat comp -o    > .katreport
###############
###############
Preparing libraries
###############
/mnt/sdc1/Illumina.GC055462-A.R1.merged.trimmed.fastq.gz
```

I thought the output prefix is the same as provided to karyon with the -o option?

thanks
Alex

**Comment by MANaranjo** [comment]
Greetings,

I have found where the error comes from. The error message comes from KAT,
since the program internally is not passing the argument correctly. I have
corrected the code and I believe it should be working now. Please update
the github using "git pull" and try again.

Thank you so much for your patience,

Miguel

**Comment by Dfupa** [comment]
To our knowledge, the issue has been successfully closed, @alexvasilikop.

If that is not the case, please, let us know and we will reopen it.
